import { Link } from "wouter";
import { motion } from "framer-motion";
import { Compass, Target, Map, Brain, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background overflow-hidden relative selection:bg-primary/20">
      {/* Decorative Background Elements */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-primary/10 blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-accent/10 blur-[120px] pointer-events-none" />

      {/* Nav */}
      <nav className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between relative z-10">
        <div className="flex items-center gap-2">
          <div className="bg-primary p-2 rounded-xl shadow-lg shadow-primary/25">
            <Compass className="h-6 w-6 text-primary-foreground" />
          </div>
          <span className="font-display font-bold text-xl tracking-tight">Productivity Hub</span>
        </div>
        <div className="flex gap-4">
          <Button variant="ghost" asChild className="rounded-xl font-medium text-muted-foreground hover:text-foreground">
            <Link href="/login">Sign In</Link>
          </Button>
          <Button asChild className="rounded-xl font-semibold shadow-lg shadow-primary/25 hover:shadow-xl hover:shadow-primary/30 transition-all hover:-translate-y-0.5">
            <Link href="/signup">Get Started</Link>
          </Button>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-6 pt-20 pb-32 relative z-10">
        <div className="text-center max-w-3xl mx-auto mt-12 md:mt-24">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <span className="inline-block py-1.5 px-4 rounded-full bg-primary/10 text-primary font-medium text-sm mb-6 border border-primary/20">
              Your AI-Powered Career Coach
            </span>
            <h1 className="text-5xl md:text-7xl font-bold tracking-tight text-foreground mb-6 leading-tight">
              Navigate Your Career with <span className="text-gradient">Precision</span>
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground mb-10 leading-relaxed max-w-2xl mx-auto">
              Stop guessing. Let AI analyze your skills, recommend ideal career paths, and generate step-by-step learning roadmaps tailored just for you.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" className="rounded-xl h-14 px-8 text-base font-semibold shadow-xl shadow-primary/30 hover:-translate-y-1 hover:shadow-2xl hover:shadow-primary/40 transition-all group" asChild>
                <Link href="/signup">
                  Start Your Journey <ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" className="rounded-xl h-14 px-8 text-base font-semibold border-2 hover:bg-secondary/50 transition-all" asChild>
                <Link href="/login">Explore Demo</Link>
              </Button>
            </div>
          </motion.div>
        </div>

        {/* Feature Grid */}
        <div className="mt-32 grid grid-cols-1 md:grid-cols-3 gap-8">
          {[
            {
              icon: Brain,
              title: "Smart Assessment",
              desc: "Deep-dive analysis of your current abilities, preferences, and background.",
              color: "text-blue-500",
              bg: "bg-blue-500/10",
              border: "border-blue-500/20"
            },
            {
              icon: Target,
              title: "Gap Analysis",
              desc: "Identify exactly what skills you lack to land your dream role in tech.",
              color: "text-cyan-500",
              bg: "bg-cyan-500/10",
              border: "border-cyan-500/20"
            },
            {
              icon: Map,
              title: "Custom Roadmaps",
              desc: "Step-by-step learning plans generated by AI to guide your transition.",
              color: "text-indigo-500",
              bg: "bg-indigo-500/10",
              border: "border-indigo-500/20"
            }
          ].map((feature, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 + i * 0.1 }}
              className={`p-8 rounded-3xl glass-card border-2 hover:-translate-y-1 transition-all duration-300 ${feature.border}`}
            >
              <div className={`w-14 h-14 rounded-2xl ${feature.bg} flex items-center justify-center mb-6`}>
                <feature.icon className={`h-7 w-7 ${feature.color}`} />
              </div>
              <h3 className="text-xl font-bold text-foreground mb-3">{feature.title}</h3>
              <p className="text-muted-foreground leading-relaxed">{feature.desc}</p>
            </motion.div>
          ))}
        </div>
      </main>

      <footer className="relative z-10 border-t border-border/60">
        <div className="mx-auto flex h-16 max-w-7xl items-center px-6">
          <p className="text-sm text-muted-foreground">
            © {new Date().getFullYear()} Productivity Hub. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
